title: Vishal Upendran
description: Senior Research Fellow, Inter Universtiy Centre for Astronomy and Astrophysics, Pune, India - 411007
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman